trust setting updated
CA certs have trust setting CT,, and intermediate certificates have u,u,u.
Different directories created for CA and intermediate certificates

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -13,28 +13,47 @@ fi
 
 # Downloading the letsencrypt certificates
 echo "Downloading the letsencrypt certificates"
-DIR="certs"
+DIR1="certs/CA"
+# CA certificates
 CERT1="https://letsencrypt.org/certs/isrgrootx1.pem.txt"
-CERT2="https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt"
-CERT3="https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt"
-CERT4="https://letsencrypt.org/certs/trustid-x3-root.pem.txt"
-cd $DIR
-#wget_output=$(wget -P "$DIR" "$CERT1" "$CERT2" "$CERT3" "$CERT4")
+CERT2="https://letsencrypt.org/certs/trustid-x3-root.pem.txt"
+
+DIR2="certs/intermediate"
+# Intermediate certificates
+CERT3="https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt"
+CERT4="https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt"
+
+wget_output=$(wget -P "$DIR1" "$CERT1" "$CERT2")
 if [ $? -ne 0 ]; 
 then
 	echo "Certificates NOT FOUND." 
 else
-	echo "Certificates downloaded."
+	echo "CA Certificates downloaded."
+fi
+
+wget_output=$(wget -P "$DIR2" "$CERT3" "$CERT4")
+if [ $? -ne 0 ]; 
+then
+	echo "Certificates NOT FOUND." 
+else
+	echo "Intermediate Certificates downloaded."
 fi
 
 
 # Importing the certificates
 echo "Importing the downloaded certificates into NSS Database"
-for file in certs/*; do
+for file in certs/CA/*; do
   file=${file##*/}
   # Removing the file extension (.pem.txt) from certificates
   name=${file%.pem.txt}
-  certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/"$file" -t "CT,,"
-  #below command for local testing - Rishabh
-  #certutil -A -d sql:${HOME}/.pki/nssdb -n "$name" -i certs/"$file" -t "CT,,"
+  certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/CA/"$file" -t "CT,,"
+  #certutil -A -d sql:${HOME}/.pki/nssdb -n "$name" -i certs/CA/"$file" -t "CT,,"
+done
+
+for file in certs/intermediate/*; do
+  file=${file##*/}
+  # Removing the file extension (.pem.txt) from certificates
+  name=${file%.pem.txt}
+  certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/intermediate/"$file" -t "u,u,u"
+  #certutil -A -d sql:${HOME}/.pki/nssdb -n "$name" -i certs/intermediate/"$file" -t "u,u,u"
 done
