reformatting

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,45 +2,39 @@
 
 # This script needs to be run as root
 echo "Checking if the script is run as root."
-if [[ $EUID -ne 0 ]]; 
-then
-  echo -e "This script should be run as root. \n"
-  exit 
+if [[ $EUID -ne 0 ]]; then
+    echo -e "This script should be run as root. \n"
+    exit
 else
-  echo -e "This script is run as root. Good to go. \n"
+    echo -e "This script is run as root. Good to go. \n"
 fi
 
 #Installing for client or server?
 read -p "Installing for server or client? Type (sS/cC) " answer
 
-
 # Checking if IPsec is installed
 echo "Checking if IPsec is installed"
 ipdir="/etc/ipsec.d"
-if [ ! -d "$ipdir" ] 
-then
-	echo "Directory /etc/ipsec.d DOES NOT exists. Please install IPsec (https://libreswan.org)"
-  echo "For Fedora - dnf -y install libreswan-3.*"
-  echo "For Centos - yum -y install libreswan-3.*"
-  echo "For Ubuntu - apt-get -y install libreswan"
-  exit
+if [ ! -d "$ipdir" ]; then
+    echo "Directory /etc/ipsec.d DOES NOT exists. Please install IPsec (https://libreswan.org)"
+    echo "For Fedora - dnf -y install libreswan-3.*"
+    echo "For Centos - yum -y install libreswan-3.*"
+    echo "For Ubuntu - apt-get -y install libreswan"
+    exit
 else
-	echo -e "IPsec is installed. \n"
+    echo -e "IPsec is installed. \n"
 fi
-
 
 #Checking for any existing OE connections
 echo -e "Checking for any existing OE connections"
 oeExisting=$(ipsec traffic)
-if [ -z "$oeExisting" ]; 
-then
-  echo "No existing OE connections found. Good to go."
+if [ -z "$oeExisting" ]; then
+    echo "No existing OE connections found. Good to go."
 else
-  echo "Existing OE Connections Found. Stopping the connections."
-  #Stopping the existing OE connections
-  ipsec restart
+    echo "Existing OE Connections Found. Stopping the connections."
+    #Stopping the existing OE connections
+    ipsec restart
 fi
-
 
 # Downloading the letsencrypt certificates
 echo -e "\nDownloading the letsencrypt certificates"
@@ -62,26 +56,23 @@ rm -rf "$DIR2"
 
 # Downloading the CA certificates
 wget_output=$(wget -q -P "$DIR1" "$CERT1" "$CERT2")
-if [ $? -ne 0 ]; 
-then
-	echo "Certificates NOT Found OR Saving the certificates in directory failed"
-  echo "try running the script with 'sudo' (root privileges)"
-  exit 
+if [ $? -ne 0 ]; then
+    echo "Certificates NOT Found OR Saving the certificates in directory failed"
+    echo "try running the script with 'sudo' (root privileges)"
+    exit
 else
-	echo "CA Certificates downloaded."
+    echo "CA Certificates downloaded."
 fi
 
 # Downloading the Intermediate certificates
 wget_output=$(wget -q -P "$DIR2" "$CERT3" "$CERT4")
-if [ $? -ne 0 ]; 
-then
-	echo "Certificates NOT Found OR Saving the certificates in directory failed"
-  echo "try running the script with 'sudo' (root privileges)"
-  exit 
+if [ $? -ne 0 ]; then
+    echo "Certificates NOT Found OR Saving the certificates in directory failed"
+    echo "try running the script with 'sudo' (root privileges)"
+    exit
 else
-	echo -e "Intermediate Certificates downloaded. \n"
+    echo -e "Intermediate Certificates downloaded. \n"
 fi
-
 
 # Initializing the nss database
 echo "Initializing the nss database"
@@ -91,29 +82,27 @@ echo
 # Importing the CA certificates
 echo "Importing the downloaded certificates into NSS Database"
 for file in certs/CA/*; do
-  file=${file##*/}
-  # Removing the file extension (.pem.txt) from certificates
-  name=${file%.pem.txt}
-  certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/CA/"$file" -t "CT,,"
+    file=${file##*/}
+    # Removing the file extension (.pem.txt) from certificates
+    name=${file%.pem.txt}
+    certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/CA/"$file" -t "CT,,"
 done
 echo "CA certificates Imported successfully."
 
 # Importing the Intermediate certificates
 for file in certs/intermediate/*; do
-  file=${file##*/}
-  # Removing the file extension (.pem.txt) from certificates
-  name=${file%.pem.txt}
-  certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/intermediate/"$file" -t "u,u,u"
+    file=${file##*/}
+    # Removing the file extension (.pem.txt) from certificates
+    name=${file%.pem.txt}
+    certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/intermediate/"$file" -t "u,u,u"
 done
 echo -e "Intermediate certificates Imported successfully. \n"
 
-
 #Copying the required configuration
-if [ "$answer" = "s" ] || [ "$answer" = "S" ];
-then
-  configFile="config/oe-letsencrypt-server.conf"
+if [ "$answer" = "s" ] || [ "$answer" = "S" ]; then
+    configFile="config/oe-letsencrypt-server.conf"
 else
-  configFile="config/oe-letsencrypt-client.conf"
+    configFile="config/oe-letsencrypt-client.conf"
 fi
 
 cp "$configFile" "$ipdir"
@@ -121,35 +110,30 @@ cp "$configFile" "$ipdir"
 echo "Saving the required configuration"
 echo -e "$configFile configuration saved in $ipdir \n"
 
-
 #Restarting Ipsec
 echo -e "Restarting Ipsec \n"
 ipsec restart
 
-
 #Establishing an OE connection
 echo -e "Establishing an OE connection. \n"
-if [ "$answer" = "c" ] || [ "$answer" = "C" ];
-then
-  #Get the IP of server
-  getIP=$(curl ifconfig.me)
-  
-  #Establish an OE connection in quiet mode
-  ##Take server IP as user input (once the initial testing completes)
-  ipsec whack --oppohere "$getIP" --oppothere 193.110.157.131 > /dev/null
-fi
+if [ "$answer" = "c" ] || [ "$answer" = "C" ]; then
+    #Get the IP of server
+    getIP=$(curl ifconfig.me)
 
+    #Establish an OE connection in quiet mode
+    ##Take server IP as user input (once the initial testing completes)
+    ipsec whack --oppohere "$getIP" --oppothere 193.110.157.131 >/dev/null
+fi
 
 #Checking the success of establishing OE connection
 echo -e "\nChecking the success of establishing OE connection \n"
 oeSuccess=$(ipsec traffic)
-if [ -z "$oeSuccess" ]; 
-then
-  echo -e "Failed to establish an OE connection. \n"
-  exit
+if [ -z "$oeSuccess" ]; then
+    echo -e "Failed to establish an OE connection. \n"
+    exit
 else
-  echo -e "OE Connection established successfully \n"
-  #Displaying connection status
-  echo -e "Displaying connection status \n"
-  ipsec traffic
+    echo -e "OE Connection established successfully \n"
+    #Displaying connection status
+    echo -e "Displaying connection status \n"
+    ipsec traffic
 fi
