letsencrypt: multiple issues fixes
letsencrypt: add checks for tmpdir creation
letsencrypt: give clear error exit code in case of error
letsencrypt: simplify logics in db check
letsencrypt: use correct IPSEC_CONFDDIR, not hardcodes
letsencrypt: do not mangle root crontab if there is /etc/cron.d

diff --git a/programs/letsencrypt/letsencrypt.in b/programs/letsencrypt/letsencrypt.in
--- a/programs/letsencrypt/letsencrypt.in
+++ b/programs/letsencrypt/letsencrypt.in
@@ -35,19 +35,20 @@ HostName=$2
 check_root() {
     # Checking if the command is run as root, This command needs to be run as root
     if [ ${EUID} -ne 0 ]; then
-        echo "This command should be run as root."
-        exit
+	echo "This command should be run as root."
+	exit 1
     fi
 }
 
 # function for testing OE connection
 test() {
     # Checking for any existing OE connections
-    oeExisting=$(ipsec traffic | grep private)
-    if [ ! -z "$oeExisting" ]; then
-        echo "Existing OE Connections Found. Please stop the connections using 'ipsec restart' and try again."
-        echo "$oeExisting"
-        exit
+    oeExisting=$(ipsec trafficstatus | grep private)
+    if [ ! -z "${oeExisting}" ]; then
+	echo "Existing OE Connections Found."
+	echo "Please stop the connections using 'ipsec restart' and try again."
+	echo "${oeExisting}"
+	exit 1
     fi
 
     # Establishing an OE connection and sending pings to letsencrypt.libreswan.org server
@@ -55,24 +56,25 @@ test() {
     ping -4 -c 5 letsencrypt.libreswan.org &>/dev/null
 
     # Checking the success of establishing OE connection
-    oeSuccess=$(ipsec traffic | grep private)
-    if [ -z "$oeSuccess" ]; then
-        echo "Failed to establish an OE connection. try 'ipsec restart' and test again using 'ipsec letsencrypt --test'."
-        exit
+    oeSuccess=$(ipsec trafficstatus | grep private)
+    if [ -z "${oeSuccess}" ]; then
+	echo "Failed to establish an OE connection."
+	echo "Try 'ipsec restart' and test again using 'ipsec letsencrypt --test'."
+	exit 1
     else
-        echo "OE Connection established successfully."
-        # Displaying connection status
-        ipsec traffic | grep private
+	echo "OE Connection established successfully."
+	# Displaying connection status
+	ipsec trafficstatus | grep private
     fi
 }
 
 # Function for performaing Initial setup
 setup() {
     # Installing for client or server?
-    if [ "$ServerClient" = "--client" ]; then
-        echo "Installing for Client."
+    if [ "${ServerClient}" = "--client" ]; then
+	echo "Installing for Client."
     else
-        echo "Installing for Server."
+	echo "Installing for Server."
     fi
 
     # Downloading the letsencrypt certificates
@@ -81,66 +83,75 @@ setup() {
     # set secure umask
     umask 077
 
-    DIR1=$(mktemp -d)
-    DIR2=$(mktemp -d)
+    CERTDIR1=$(mktemp -d)
+    if [ $? -gt 0 ]; then
+	echo "ERROR: could not crete temp directory"
+	exit 1
+    fi
+    CERTDIR2=$(mktemp -d)
+    if [ $? -gt 0 ]; then
+	echo "ERROR: could not crete temp directory"
+	exit 1
+    fi
 
     # Downloading the CA certificates
-    wget_output=$(wget -q -P "$DIR1" "$CERT1" "$CERT2")
+    wget_output=$(wget -q -P "${CERTDIR1}" "${CERT1}" "${CERT2}")
     if [ $? -ne 0 ]; then
-        echo "CA Certificates NOT Found OR Saving the certificates in directory failed."
-        exit
+	echo "ERROR: CA Certificates NOT Found OR Saving the certificates in directory failed."
+	exit 1
     fi
 
     # Downloading the Intermediate certificates
-    wget_output=$(wget -q -P "$DIR2" "$CERT3" "$CERT4")
+    wget_output=$(wget -q -P "${CERTDIR2}" "${CERT3}" "${CERT4}")
     if [ $? -ne 0 ]; then
-        echo "Intermediate Certificates NOT Found OR Saving the certificates in directory failed."
-        exit
+	echo "ERROR: Intermediate Certificates NOT Found OR"
+	echo "Saving the certificates in directory failed."
+	exit 1
     fi
 
     # Checking if nss database exists
-    dbFileCount=$(ls "@IPSEC_NSSDIR@"/*.db 2>/dev/null | wc -l)
-    if [ $dbFileCount -eq 0 ]; then
-        # NSS database does not exist. Initializing the nss database
-        ipsec initnss
+    dbFileCheck=$(ls "@IPSEC_NSSDIR@"/*.db 2>/dev/null)
+    if [ -z "${dbFileCheck}" ]; then
+	# NSS database does not exist. Initializing the nss database
+	ipsec initnss
     fi
 
     # Importing the CA certificates in NSS database
     echo "Importing the downloaded certificates into the database"
-    for file in "$DIR1"/*; do
-        file=${file##*/}
-        certutil -A -d "sql:@IPSEC_NSSDIR@" -n "${file%.pem.txt}" -i "$DIR1"/"$file" -t "CT,,"
+    for file in "${CERTDIR1}"/*; do
+	file=${file##*/}
+	certutil -A -d "sql:@IPSEC_NSSDIR@" -n "${file%.pem.txt}" -i "${CERTDIR1}"/"${file}" -t "CT,,"
     done
 
     # Importing the Intermediate certificates in NSS database
-    for file in "$DIR2"/*; do
-        file=${file##*/}
-        certutil -A -d "sql:@IPSEC_NSSDIR@" -n "${file%.pem.txt}" -i "$DIR2"/"$file" -t "u,u,u"
+    for file in "${CERTDIR2}"/*; do
+	file=${file##*/}
+	certutil -A -d "sql:@IPSEC_NSSDIR@" -n "${file%.pem.txt}" -i "${CERTDIR2}"/"${file}" -t "u,u,u"
     done
 
     # restore umask
     umask ${umask}
 
     # Copying the required configuration
-    if [ "$ServerClient" = "--server" ]; then
-        configFile="@FINALDOCDIR@/examples/oe-letsencrypt-server.conf"
-        configFileName="oe-letsencrypt-server.conf"
+    if [ "${ServerClient}" = "--server" ]; then
+	configFile="@FINALDOCDIR@/examples/oe-letsencrypt-server.conf"
+	configFileName="oe-letsencrypt-server.conf"
     else
-        configFile="@FINALDOCDIR@/examples/oe-letsencrypt-client.conf"
-        configFileName="oe-letsencrypt-client.conf"
+	configFile="@FINALDOCDIR@/examples/oe-letsencrypt-client.conf"
+	configFileName="oe-letsencrypt-client.conf"
     fi
 
     echo "Saving the required configuration"
-    cp "$configFile" "@IPSEC_NSSDIR@"
+    cp "${configFile}" "@IPSEC_CONFDDIR@/"
 
-    # restoring the security context of @IPSEC_NSSDIR@/$configFileName using restorecon.
+    # restoring the security context of @IPSEC_CONFDDIR@/$configFileName using restorecon.
     checkRestorecon=$(which restorecon 2>/dev/null)
     if [ -n "${checkRestorecon}" -a -x "${checkRestorecon}" ]; then
-        restorecon "@IPSEC_NSSDIR@/$configFileName"
+	restorecon "@IPSEC_CONFDDIR@/$configFileName"
     fi
 
     # Removing the temporary directories
-    rm -rf "$DIR1 $DIR2"
+    rm -rf "${CERTDIR1}" "${CERTDIR2}"
 
     echo "To confirm the success try running 'ipsec letsencrypt --test' on the client"
 }
@@ -150,31 +161,35 @@ generate_certificate() {
     # Generating the certificate using Certbot
     certBotInstalled=$(which certbot 2>/dev/null)
     if [ -n "${certBotInstalled}" -a -x "${certBotInstalled}" ]; then
-        certbot certonly --webroot -d "$HostName"
+	certbot certonly --webroot -d "${HostName}"
     else
-        echo "Certbot not installed. Please install Certbot and try again."
-        exit
+	echo "ERROR: Certbot not installed. Please install Certbot and try again."
+	exit 1
     fi
 
     # set secure umask
     umask 077
 
-    DIR=$(mktemp -d)
+    CERTDIR=$(mktemp -d)
+    if [ $? -gt 0 ]; then
+	echo "ERROR: could not crete temp directory"
+	exit 1
+    fi
 
-    wget_output=$(wget -q -P "$DIR" "$CERT4")
+    wget_output=$(wget -q -P "${CERTDIR}" "${CERT4}")
     if [ $? -ne 0 ]; then
-        echo "Certificates NOT Found OR Saving the certificate in directory failed"
-        exit
+	echo "ERROR: Certificates NOT Found OR Saving the certificate in directory failed"
+	exit 1
     fi
 
     # Now generating the #pkcs12 (.p12) file
-    LetsEncryptCertDir="/etc/letsencrypt/live/$HostName"
+    LetsEncryptCertDir="/etc/letsencrypt/live/${HostName}"
 
-    openssl pkcs12 -export -inkey "$LetsEncryptCertDir/privkey.pem" -in "$LetsEncryptCertDir/fullchain.pem" -CAfile "$DIR/$CERT4NAME" -out "$LetsEncryptCertDir/generatedCertificate.p12"
+    openssl pkcs12 -export -inkey "${LetsEncryptCertDir}/privkey.pem" -in "${LetsEncryptCertDir}/fullchain.pem" -CAfile "${CERTDIR}/${CERT4NAME}" -out "${LetsEncryptCertDir}/generatedCertificate.p12"
 
     # Importing the certificate in nss database
     echo "Importing the certificate in database. Password for PKCS12 file is the same as the Export Password you entered above."
-    pk12util -d "sql:@IPSEC_NSSDIR@" -i "$LetsEncryptCertDir/generatedCertificate.p12"
+    pk12util -d "sql:@IPSEC_NSSDIR@" -i "${LetsEncryptCertDir}/generatedCertificate.p12"
 
     # restore umask
     umask ${umask}
@@ -183,16 +198,23 @@ generate_certificate() {
     certutil -L -d "sql:@IPSEC_NSSDIR@"
 
     # Now generating the certbot configuration for reusing key
-    LetsEncryptConfFile="/etc/letsencrypt/renewal/$HostName.conf"
-    echo "reuse_key = True" >>"$LetsEncryptConfFile"
+    LetsEncryptConfFile="/etc/letsencrypt/renewal/${HostName}.conf"
+    echo "reuse_key = True" >>"${LetsEncryptConfFile}"
 
     # creating a crontab fot automatic cert renewals
-    echo "0 1 * * * certbot renew --deploy-hook 'ipsec letsencrypt --update-certificate $HostName'" >>cert-renewal
-    crontab cert-renewal
-    rm cert-renewal
+    if [ -d /etc/cron.d ]; then
+	if [ ! -f /etc/cron.d/ipsec-cert-renewal ]; then
+	    echo "0 1 * * * root certbot renew --deploy-hook 'ipsec letsencrypt --update-certificate ${HostName}'" \
+		>>/etc/cron.d/ipsec-cert-renewal
+	fi
+    else
+	echo "0 1 * * * certbot renew --deploy-hook 'ipsec letsencrypt --update-certificate ${HostName}'" >>cert-renewal
+	crontab cert-renewal
+	rm cert-renewal
+    fi
 
-    # Removing the temporary directories
-    rm -rf "$DIR"
+    # Removing the temporary directory
+    rm -fr "${CERTDIR}"
 
     echo "try running 'ipsec restart' to load the latest certificates"
 
@@ -205,22 +227,26 @@ update_certificate() {
     # set secure umask
     umask 077
 
-    DIR=$(mktemp -d)
+    CERTDIR=$(mktemp -d)
 
-    wget_output=$(wget -q -P "$DIR" "$CERT4")
+    wget_output=$(wget -q -P "${CERTDIR}" "${CERT4}")
     if [ $? -ne 0 ]; then
-        echo "Certificates NOT Found OR Saving the certificate in directory failed"
-        exit
+	echo "ERROR: Certificates NOT Found OR Saving the certificate in directory failed"
+	exit 1
     fi
 
     # Now generating the #pkcs12 (.p12) file
-    LetsEncryptCertDir="/etc/letsencrypt/live/$HostName"
+    LetsEncryptCertDir="/etc/letsencrypt/live/${HostName}"
 
-    openssl pkcs12 -export -inkey "$LetsEncryptCertDir/privkey.pem" -in "$LetsEncryptCertDir/fullchain.pem" -CAfile "$DIR/$CERT4NAME" -out "$LetsEncryptCertDir/generatedCertificate.p12"
+    openssl pkcs12 -export -inkey "${LetsEncryptCertDir}/privkey.pem" \
+	-in "${LetsEncryptCertDir}/fullchain.pem" \
+	-CAfile "${CERTDIR}/${CERT4NAME}" \
+	-out "${LetsEncryptCertDir}/generatedCertificate.p12"
 
     # Importing the certificate in nss database
-    echo "Importing the certificate in database. Password for PKCS12 file is the same as the Export Password you entered above."
-    pk12util -d "sql:@IPSEC_NSSDIR@" -i "$LetsEncryptCertDir/generatedCertificate.p12"
+    echo "Importing the certificate in database."
+    echo "Password for PKCS12 file is the same as the Export Password you entered above."
+    pk12util -d "sql:@IPSEC_NSSDIR@" -i "${LetsEncryptCertDir}/generatedCertificate.p12"
 
     # restore umask
     umask ${umask}
@@ -232,9 +258,9 @@ update_certificate() {
     # restarting ipsec to load all certificates
     ipsec restart
 
-    # Removing the temporary directories
-    rm -rf "$DIR"
-    
+    # Removing the temporary directory
+    rm -fr "${CERTDIR}"
+
     # To confirm the success try running the test connection script on the client
     echo "To confirm the success try running 'ipsec letsencrypt --test' on the client"
 }
@@ -244,17 +270,17 @@ manual_cert_renew() {
     # Renewing the certificate using Certbot
     certBotInstalled=$(which certbot 2>/dev/null)
     if [ -n "${certBotInstalled}" -a -x "${certBotInstalled}" ]; then
-        certbot renew --deploy-hook 'ipsec letsencrypt --update-certificate $HostName'
+	certbot renew --deploy-hook 'ipsec letsencrypt --update-certificate ${HostName}'
     else
-        echo "Certbot not installed. Please install Certbot and try again."
-        exit
+	echo "ERROR: Certbot not installed. Please install Certbot and try again."
+	exit 1
     fi
 }
 
-# function to disable ipsec by deleting the conf file in /etc/ipsec.d
+# function to disable ipsec by deleting the conf file in @IPSEC_CONFDDIR@
 disable_ipsec() {
     # Deleting the configuration files present in /etc/ipsec.d directory
-    rm -f /etc/ipsec.d/oe-letsencrypt-*.conf
+    rm -f "@IPSEC_CONFDDIR@"/oe-letsencrypt-*.conf
     echo "Please restart the IPsec service using 'ipsec restart' for changes to take effect."
 }
 
@@ -283,37 +309,36 @@ help() {
     echo "usage: 'ipsec letsencrypt --disable'"
 }
 
-case $1 in
-
-"--test")
-    check_root
-    test
-    ;;
-"--server" | "--client")
-    check_root
-    setup
-    ;;
-"--generate-certificate")
-    check_root
-    generate_certificate
-    ;;
-"--update-certificate")
-    check_root
-    update_certificate
-    ;;
-"--renew")
-    check_root
-    manual_cert_renew
-    ;;
-"--disable")
-    check_root
-    disable_ipsec
-    ;;
-"--help")
-    help
-    ;;
-*)
-    echo "[argument] $1 not found"
-    echo "try: 'ipsec letsencrypt --help' for help"
-    ;;
+case "${1}" in
+    --test)
+	check_root
+	test
+	;;
+    --server|--client)
+	check_root
+	setup
+	;;
+    --generate-certificate)
+	check_root
+	generate_certificate
+	;;
+    --update-certificate)
+	check_root
+	update_certificate
+	;;
+    --renew)
+	check_root
+	manual_cert_renew
+	;;
+    --disable)
+	check_root
+	disable_ipsec
+	;;
+    --help)
+	help
+	;;
+    *)
+	echo "[argument] \"${1}\" not found"
+	echo "try: 'ipsec letsencrypt --help' for help"
+	;;
 esac
